### ISSUE TITLE
Cannot load 2.2 framework on OS X 10.9

### ISSUE THREAD

**Issue by anddam** [Kentzo/F-Script#10]
When loading FScriptFramework.framework NSBundle in order to inject it I get an error.

The system is 10.9.3, Xcode is 5.1.1 with its tools (specifically lldb).

I tried to inject the 2.2 framework, labeled for "10.7, 10.8 and 10.9" on fscript.org, into TextEdit and got this error:

```
(lldb) po $anError
Error Domain=NSCocoaErrorDomain Code=4 "The bundle “F-Script Framework” couldn’t be loaded because its executable couldn’t be located." UserInfo=0x10023c340 {NSLocalizedFailureReason=The bundle’s executable couldn’t be located., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSBundlePath=/Library/Frameworks/FScriptFramework.framework, NSLocalizedDescription=The bundle “F-Script Framework” couldn’t be loaded because its executable couldn’t be located.}
```

The 2.1 framework version, labeled for 1.6, succesfully loads.

Full commands with actual output follow:

```
> lldb /Applications/TextEdit.app/Contents/MacOS/TextEdit
Current executable set to '/Applications/TextEdit.app/Contents/MacOS/TextEdit' (x86_64).
(lldb) expr (BOOL)[[NSBundle bundleWithPath:@"/Library/Frameworks/FScriptFramework.framework"] load]
error: use of undeclared identifier 'NSBundle'
error: 1 errors parsing expression
(lldb) r
Process 1966 launched: '/Applications/TextEdit.app/Contents/MacOS/TextEdit' (x86_64)
Process 1966 stopped
* thread #1: tid = 0xe9f9, 0x00007fff8b703a1a libsystem_kernel.dylib`mach_msg_trap + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff8b703a1a libsystem_kernel.dylib`mach_msg_trap + 10
libsystem_kernel.dylib`mach_msg_trap + 10:
-> 0x7fff8b703a1a:  ret
   0x7fff8b703a1b:  nop

libsystem_kernel.dylib`mach_msg_overwrite_trap:
   0x7fff8b703a1c:  movq   %rcx, %r10
   0x7fff8b703a1f:  movl   $0x1000020, %eax
(lldb) expr (BOOL)[[NSBundle bundleWithPath:@"/Library/Frameworks/FScriptFramework.framework"] load]
2014-05-25 19:53:49.295 TextEdit[1966:d0b] Cannot find executable for CFBundle 0x1001b9230 </Library/Frameworks/FScriptFramework.framework> (not loaded)
(BOOL) $0 = NO
(lldb) expr NSError *$anError = nil
(lldb) expr (BOOL)[[NSBundle bundleWithPath:@"/Library/Frameworks/FScriptFramework.framework"] loadAndReturnError:&$anError]
(BOOL) $1 = NO
(lldb) po $anError
Error Domain=NSCocoaErrorDomain Code=4 "The bundle ‚ÄúF-Script Framework‚Äù couldn't be loaded because its executable couldn't be located." UserInfo=0x10023c340 {NSLocalizedFailureReason=The bundle's executable couldn't be located., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSBundlePath=/Library/Frameworks/FScriptFramework.framework, NSLocalizedDescription=The bundle ‚ÄúF-Script Framework‚Äù couldn't be loaded because its executable couldn't be located.}
(lldb)
```

**Comment by anddam** [comment]
I diffed the 2.2 and 2.1 bundle and noticed that the Info.plist in FScriptFramework.framework was still declaring a value 'FScript' for key 'CFBundleExecutable', please fix this by using 'FScriptFramework' instead that is the name of the actual Mach-O file, and relase a new binary archive.

What's the rationale for the bundle name change anyway?

**Comment by Kentzo** [comment]
Please try https://github.com/Kentzo/F-Script/releases/tag/v2.2.1

**Comment by anddam** [comment]
That works, I see you reverted the bundle naming as well. Thanks for the prompt update.
